function(print_boolean prefix var)
    if (NOT "${${var}}")
        message(STATUS ${prefix} "OFF")
    else ()
        message(STATUS ${prefix} "ON")
    endif ()
endfunction(print_boolean bool_arg)

function(print_all_variables)
    # this prints out absolutely every variable, probably not desired
    get_cmake_property(_variableNames VARIABLES)
    list (SORT _variableNames)
    foreach (_variableName ${_variableNames})
        message(STATUS "${_variableName}=${${_variableName}}")
    endforeach()
endfunction(print_all_variables)

# Prints geopm configuration summary
function(geopm_print_configuration_summary)
    message(STATUS ===============================================================================)
    message(STATUS "version            : " "${VERSION}")
    message(STATUS )
    message(STATUS "CC                 : " "${CMAKE_C_COMPILER}")
    message(STATUS "CFLAGS             : " "${CMAKE_C_FLAGS}")
    message(STATUS "CXX                : " "${CMAKE_CXX_COMPILER}")
    message(STATUS "CXXFLAGS           : " "${CMAKE_CXX_FLAGS}")
    message(STATUS "F77                : " "${F77}")
    message(STATUS "FFLAGS             : " "${FFLAGS}")
    message(STATUS "LDFLAGS            : " "${LDFLAGS}")
    message(STATUS "LD_LIBRARY_PATH    : " "${LD_LIBRARY_PATH}")
    message(STATUS "LIBS               : " "${LIBS}")
    message(STATUS "FLIBS              : " "${FLIBS}")
    message(STATUS "MPI_LDFLAGS        : " "${MPI_LDFLAGS}")
    message(STATUS "MPI_LIBS           : " "${MPI_LIBS}")
    message(STATUS "MPI_CXXLIBS        : " "${MPI_CXXLIBS}")
    message(STATUS "MPI_FLIBS          : " "${MPI_FLIBS}")
    message(STATUS "MPI_FCLIBS         : " "${MPI_FCLIBS}")
    message(STATUS )
    message(STATUS "prefix             : " "${prefix}")
    message(STATUS "exec_prefix        : " "${exec_prefix}")
    message(STATUS "sbindir            : " "${sbindir}")
    message(STATUS "includedir         : " "${includedir}")
    message(STATUS "libdir             : " "${libdir}")
    message(STATUS "datarootdir        : " "${datarootdir}")
    message(STATUS "datadir            : " "${datadir}")
    message(STATUS "mandir             : " "${mandir}")
    message(STATUS )
    print_boolean("beta               : " ENABLE_BETA)
    print_boolean("debug              : " enable_debug)
    print_boolean("coverage           : " enable_coverage)
    print_boolean("mpi                : " ENABLE_MPI)
    print_boolean("overhead           : " GEOPM_OVERHEAD)
    print_boolean("ompt               : " ENABLE_OMPT)
    print_boolean("openmp             : " ENABLE_OPENMP)
    print_boolean("fortran            : " ENABLE_FORTRAN)
    message(STATUS ===============================================================================)
endfunction()
